services:
  api:
    container_name: mutants-api
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo-db
  mongo-db:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - '27017:27017'